// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ADescriptions: typeof import('@arco-design/web-vue')['Descriptions']
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATable: typeof import('@arco-design/web-vue')['Table']
    BaseDrawDown: typeof import('./src/components/base-draw-down/index.vue')['default']
    BaseEditInfo: typeof import('./src/components/base-edit-info/index.vue')['default']
    BaseSignForm: typeof import('./src/components/base-sign-form/index.vue')['default']
    BaseSignIn: typeof import('./src/components/base-sign-in/index.vue')['default']
    'BaseSignIn copy': typeof import('./src/components/base-sign-in copy/index.vue')['default']
    BaseSignOut: typeof import('./src/components/base-sign-out/index.vue')['default']
    'BaseSignOut copy': typeof import('./src/components/base-sign-out copy/index.vue')['default']
    BaseSignUp: typeof import('./src/components/base-sign-up/index.vue')['default']
    'BaseSignUp copy': typeof import('./src/components/base-sign-up copy/index.vue')['default']
    BaseSwitch: typeof import('./src/components/base-switch/index.vue')['default']
    BaseUserInfo: typeof import('./src/components/base-user-info/index.vue')['default']
    'BaseUserInfo copy': typeof import('./src/components/base-user-info copy/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
